version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000" 
    environment:
      - DATABASE_URL="postgresql://neondb_owner:npg_6e7oTMFKPnku@ep-solitary-truth-a1iyvkas-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - JWT_SECRET="your-super-secret-jwt-key-change-in-production"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL="http://localhost:3000"
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
